### ISSUE TITLE
Issue with compiling non-prettified tags

### ISSUE THREAD

**Issue by pavel** [riot/compiler#65] opened 2016-04-21 15:29 UTC
Consider following 2 examples.

Example 1:
```html
<!DOCTYPE html>
<html>
<head>
	<title>Riot test</title>
</head>
<body>
	<test/>

	<template id="test">
		<test>
			<h3>Hi, {name}!</h3>
			<script>
				this.name = "Mike";
			</script>
		</test>
	</template>

	<script src="https://cdn.jsdelivr.net/riot/2.3/riot+compiler.min.js"></script>

	<script>
		riot.compile(test.innerHTML);
		riot.mount("*");
	</script>
</body>
<html>
```
Output is: Hi, Mike!

Example 2:
```html
<!DOCTYPE html>
<html>
<head>
	<title>Riot test</title>
</head>
<body>
	<test/>

	<template id="test">
		<test><h3>Hi, {name}!</h3><script>this.name = "Mike";</script></test>
	</template>

	<script src="https://cdn.jsdelivr.net/riot/2.3/riot+compiler.min.js"></script>

	<script>
		riot.compile(test.innerHTML);
		riot.mount("*");
	</script>
</body>
<html>
```
Output is: Hi, !

This is an issue especially when one uses [pug](https://github.com/pugjs), as, by default, it produces non-prettified HTML.

**Comment by pavel** [comment] 2016-04-21 23:47
Also the issue is true for minified pages, for example, a page minified via `html-minifier` with `--minify-js` option.

**Comment by aMarCruz** [comment] 2016-04-25 22:25
@pavel , this specified in the compiler [guide here]https://github.com/riot/compiler/blob/master/doc/guide.md), in the sections "Indentation" and "The Untagged JavaScript Block".
This is by design because it is the only way we can identify custom riot tags. Any minification should happen _after_ the compilation by riot.

I'll close this issue now, feel free to reopen it if you consider it necessary.

**Closed by aMarCruz** 2016-04-25 22:25 UTC
Labels: question

**Comment by pavel** [comment] 2016-04-26 05:03
@aMarCruz What I'd like to raise here is:

1) In `Jade` (aka Pug) section, there's no note about using `-P`(pretty print) flag, to make it work.
2) No `Caveats/Troubleshoot` section, that may clear it out from the start.
3) Error message does not point in this direction, which leads to time consuming debugging.

Thanks.

**Comment by GianlucaGuarini** [comment] 2016-04-26 06:11
@pavel @aMarCruz probably it's worth to update our [doc](https://github.com/riot/riot.github.io) any pull request is really welcome
