### ISSUE TITLE
babel script: 'import' in tag script will get error

### ISSUE THREAD

**Issue by txchen** [riot/compiler#21] opened 2015-11-11 07:14 UTC
environment: riot 2.3.1, webpack latest, babel v6.
tag example:
```
<mytag>
  <script type="babel">
  import foo from './bar'
  // some other fancy code
  </script>
</mytag>
```

This will get error when running babel: `error 'import' and 'export' may only appear at the top level`

**Comment by appedemic** [comment] 2015-11-11 12:03
This is caused by the babel parser. babel 6 doesn't allow toplevel this and destroys references (#15) so the parser wraps code in a function. The import statements are executed within this wrapper function and that is causing the error.

**Comment by txchen** [comment] 2015-11-11 17:46
I think previously it works because of the blacklist 'strict' setting, not sure if babel 6 still have something similar.

**Comment by aMarCruz** [comment] 2015-11-12 02:48
@appedemic , it is true. I'm not a babel user, but in tests babel-core 5.8.x was the cleaner and faster solution, v6 was complicated and slower.

**Comment by txchen** [comment] 2015-11-12 03:25
@aMarCruz right, I also noticed that v6 is slower, but seems v5 is not maintained any more, I think we still need to go with v6.

**Comment by aMarCruz** [comment] 2015-11-12 04:44
It seems so. I'm closing this issue by now.

**Comment by txchen** [comment] 2015-11-12 05:01
@aMarCruz why close this? We don't want to support babel v6, then?

**Comment by GianlucaGuarini** [comment] 2015-11-12 07:13
@aMarCruz I want to reopen this issue I think we can fix this as well.
@txchen have you tried also using the include outside of your tags?
```html
import foo from './bar'
<mytag>
  <script type="babel">
  // some other fancy code
  </script>
</mytag>
```
I will try asking support on the babel repo

**Comment by GianlucaGuarini** [comment] 2015-11-12 07:32
I have just seen that [babeljs has already fixed the issue](https://github.com/babel/babel/blob/master/CHANGELOG.md#613) we just need to implement this option :tada:

**Comment by aMarCruz** [comment] 2015-11-12 07:35
:+1:

**Comment by appedemic** [comment] 2015-11-12 09:40
Yeah, "Add allowTopLevelThis option to babel-plugin-transform-es2015-modules-commonjs" :dancer: 

I can probably create a patch today

**Comment by appedemic** [comment] 2015-11-12 13:05
Currently there is no way to add plugin options to a preset, so this allowTopLevelThis cannot be used directly with presets:['es2015']. There is an ongoing discussion about how to support this...

**Comment by aMarCruz** [comment] 2015-11-12 16:13
@appedemic , thanks. we hope your PR.

**Comment by txchen** [comment] 2015-11-12 17:19
@GianlucaGuarini  putting import in the very beginning of the tag file does not work, riot-loader will throw error:

ERROR in ./src/view/detail-view.html
Module parse failed: /Users/txchen/GithubCode/feplay/riot_webpack/node_modules/riotjs-loader/index.js!/Users/txchen/GithubCode/feplay/riot_webpack/src/view/detail-view.html Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import stores from '../stores'
| riot.tag2('detail-view', '<h2>{_post.title}</h2> <p>{_post.content}</p> <p>{_post.likes} Likes</p> <a if="{opts.data > 1}" href="#detail/{opts.data - 1}">Previous Post</a> | <a if="{opts.data < _total}" href="#detail/{opts.data - -1}">Next Post</a>', '', '', function(opts) {
|   var _this = this;
 @ ./src/riotTags.js 9:0-34

**Comment by GianlucaGuarini** [comment] 2015-11-14 16:33
I've asked support to the babel maintainers https://github.com/babel/babel/issues/3055 I hope to get a valid answer soon

**Comment by appedemic** [comment] 2015-11-16 21:11
For fun I created a modified es2015 preset: https://github.com/appedemic/babel-preset-es2015-riot

However, npm has some trouble accepting logins right now so I can't publish this as a package right now

**Comment by andyrj** [comment] 2015-11-23 01:15
is babel-preset-es2015-riot still going to be pushed to npm?

**Comment by appedemic** [comment] 2015-11-23 07:30
Right now it's not possible to send the allowTopLevelThis option to the right plugin within the preset. I've been thinking, if we add an option to the compiler where the end user can supply a list of presets/plugins to use, it would be the most flexible.

For example, I really like to use some ES7 features (async/await and Object.entries) and they are not part of the es2015 preset, but stage-0 and stage-3. For these features I need to add a preset/plugin to the babel compiler.

I could create a pr that takes the compiler plugins/preset options from the configuration and defaults to es2015. Then, I can supply my desired configuration into riotify and it will be passed on nicely.

**Comment by aMarCruz** [comment] 2015-11-23 17:02
There is an idea of a possible system of plugins that should solve some issues like this in https://github.com/riot/riot/pull/1272.
It is likely that something like that is implemented.

**Comment by appedemic** [comment] 2015-11-27 16:46
Ok, so the plan is to make packages for the parsers? So to have some npm packages like _riot-compiler-parser-babel_ and _riot-compiler-parser-jade_, etc.? And provide some mechanism to configure the compiler with said packages? 

```
riot.compiler.use(require('riot-compiler-parser-babel')({ presets: ['es2015'] }))
```

If implemented correctly it would be a nice future-ready solution

**Comment by aMarCruz** [comment] 2015-11-27 17:26
@appedemic , yeah, I hope soon, after stabilizing the current version, the changes have been many.

**Comment by GianlucaGuarini** [comment] 2015-12-06 20:39
Ok this issue was solved in the `es6` branch @aMarCruz can you review my changes and make the new releases of the `riot-tmpl` and `riot-compiler`? I would like compile riotjs using rollup and also update the cli as well adding the `debug` compiler option

**Comment by aMarCruz** [comment] 2015-12-06 20:46
@GianlucaGuarini sure. the `dist/riot.*.js` will be generated anyway?

**Comment by GianlucaGuarini** [comment] 2015-12-06 20:47
Let's keep it for now we will delete it if everything will run smooth

**Comment by aMarCruz** [comment] 2015-12-06 20:48
ok

**Comment by GianlucaGuarini** [comment] 2015-12-07 17:49
@aMarCruz can we infer the url param for the compile method from the first one ( src ) at least on node?

**Comment by GianlucaGuarini** [comment] 2015-12-07 18:18
@appedemic can we use your riot-bable preset in our official repo? I woul like to publish it on npm with the new release of the compiler

**Comment by aMarCruz** [comment] 2015-12-07 19:41
@GianlucaGuarini , no way to infer the url from the `src` parameter, it can come from anywhere.

**Comment by GianlucaGuarini** [comment] 2015-12-12 23:28
@appedemic I have published on npm the riot-preset based on your setup thank you and feel free to pull request on [this repo](https://github.com/riot/babel-preset-es2015-riot)

**Comment by creatorrr** [comment] 2015-12-23 08:27
@appedemic I thought the function wrapper was only necessary for [this bug](15). The top-level this issue should be resolved now with the babel-riot preset. Removing the wrapper function from the compiled templates should allow `import`s.

If not, for now we could revert to using `require( _module )` in tags instead of `import`.

**Comment by GianlucaGuarini** [comment] 2015-12-23 08:36
@creatorrr you are right this bug was fixed and it can be closed

**Closed by GianlucaGuarini** 2015-12-23 08:36 UTC
