### ISSUE TITLE
case where <yield> causes "Uncaught SyntaxError: Unexpected token )"

### ISSUE THREAD

**Issue by btakita** [riot/compiler#48] opened 2016-01-20 01:40 UTC
here is the template html:

```html
<onboarding-new>
  <yield/>
</onboarding-new>
```

here is the yielded html 

```html
        <form novalidate="" data-parsley-validate="" action="/application" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="x7LlLKnR/gN0WI//lE5RCidplKI4OWPU97A9f1UI8qAPv5ufcbpNLVh4G0Ai5a5UwvmDO6Iv4kz+Rm2GqywLNw==">  <fieldset>
            <section>
              <label>
                Password
                <input placeholder="**********" required="required" id="password" data-parsley-pattern=".{8,}$" data-parsley-trigger="focusin" data-parsley-pattern-message="Your password must be at least 8 characters and contain at least one upper case letter, one lower case letter, and one number." data-parsley-required-message="Your password must be at least 8 characters and contain at least one upper case letter, one lower case letter, and one number." type="password" name="application[password]" data-parsley-id="4">
              </label>
              <label>
                Confirm Password
                <input placeholder="**********" required="required" data-parsley-equalto="#password" data-parsley-equalto-message="Your passwords do not match." data-parsley-required-message="Your passwords do not match." type="password" name="application[password_confirmation]" id="application_password_confirmation" data-parsley-id="6">
              </label>
            </section>
          </fieldset>
        </form>
```

here is the anonymous function with the error

```javascript
(function(E
/**/) {
return [".",function(v){v=(8,);return v||v===0?v:""}.call(this),"$"].join("");
})
```

**Comment by aMarCruz** [comment] 2016-01-20 02:51
@btakita this is a `riot-tmpl` issue. Anyway, at first glance I see you are using an invalid expression: `".{8,}$"`. You must escape literal opening brackets that conflicts with the current riot brackets. Please test changing it to: `".\{8,}$"`

**Comment by btakita** [comment] 2016-01-20 20:30
i will. to give you some context, i've been porting a rails/jquery/react
app to use riotjs.

this logic has worked with the browser.

is this a stance that you want riot to take? if yes, maybe a more explicit
error would be better?

it takes a certain amount of skill & persistence to isolate this issue in
certain legacy apps. i would imagine, some developers encountering such a
case will fall into a rathole and/or reject riotjs as being "broken".

On Tue, Jan 19, 2016 at 9:51 PM, Alberto Martínez <notifications@github.com>
wrote:

> @btakita <https://github.com/btakita> this is a riot-tmpl issue. Anyway,
> at first glance I see you are using an invalid expression: ".{8,}$". You
> must escape literal opening brackets that conflicts with the current riot
> brackets. Please test changing it to: ".\{8,}$"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/riot/compiler/issues/48#issuecomment-173068725>.
>



-- 
Brian Takita
briantakita.com
about.me/brian_takita

**Comment by btakita** [comment] 2016-01-20 20:33
here is the haml source. as you can see, forcing the programmer to escape braces is undesirable...

```haml
      %section
        %label
          Password
          = f.password_field :password,
            placeholder: "**********",
            required: "",
            id: "password",
            data: { parsley_pattern: ".{8,}$",
            parsley_trigger: "focusin",
            parsley_pattern_message: "Your password must be at least 8 characters and contain at least one upper case letter, one lower case letter, and one number.",
            parsley_required_message: "Your password must be at least 8 characters and contain at least one upper case letter, one lower case letter, and one number."}

        %label
          Confirm Password
          = f.password_field :password_confirmation,
            placeholder: "**********",
            required: "",
            data: { parsley_equalto: "#password",
            parsley_equalto_message: "Your passwords do not match.",
            parsley_required_message: "Your passwords do not match."}
```

**Comment by aMarCruz** [comment] 2016-01-20 21:18
@btakita , this behavior is by design, riot need to work in very different frameworks/environments and expressions can appear almost anywhere in the tag, so we can't parse special cases. However, you don't need escape the `{` char if you change the riot brackets to anything else, ex: "${ }", "(% %)", etc.

Please read https://github.com/riot/tmpl/blob/dev/doc/CHANGES.md for restrictions. It also applies to expressions in the compiler.

**Comment by btakita** [comment] 2016-01-20 22:57
@aMarCruz ok, it's making sense now.

to distill why:

riotjs uses brackets `{}` by default for variable interpolation. you must escape the variable interpolation characters if you don't want riot to process them.

but then, why is this a parse error & not riot interpolating the variable?

**Comment by aMarCruz** [comment] 2016-01-20 23:35
@btakita , riot replaces `<yield/>` with the innerHTML of the _html_ element where the riot tag is mounting so, if I understand your first example, with no more than the `<yield/>`, the html is rewritten as-is, including the error in the expression.

In your second example, I guess riot is trying to evaluate `data` as a [shorthand](http://riotjs.com/guide/#tag-syntax) so you need escape both opening braces: `data: \{` and `.\{8,}$`..., but I don't know about haml, maybe it is a bug in riot. Please post the raw output from haml and I will tell yow.

> but then, why is this a parse error & not riot interpolating the variable?
I don't know what you mean, I can't see variables in `8,` , only invalid JavaScript.

...and about why-riot? this is from my cookbook:
Ingredients:
* 2 js programmers with no knowledge of reat nor riot
* specs of a small size web app (addressbook?)

Preparation:
Give each programmer the specs, put them to work, one with react, the other with riot, and cook their work over low heat, say ... three days?
Try the results, then decide :wink: 

Seriously:
I like understand what I'm doing, and it is a big big task with heavy tools like React or Angular.
It took me a few days learn riot and its most important gotchas, ~2 weeks understand the compiler and having my first rewrite working. riot is simple and powerfull.

**Comment by btakita** [comment] 2016-01-21 03:12
> data: \{ and .\{8,}$

for some unknown reason, `\\` is needed to work:
`data: \\{ and .\\{8,}$`

i'm on board with riot in most if not all cases one would use angular & react.

i'm just presented with a situation & am trying to create a narrative on why `{}` needs to be escaped.

**Comment by aMarCruz** [comment] 2016-01-21 16:10
@btakita , better stay out of troubles and use another riot brackets.
For the CLI use something like `--brackets "#{ }"`. In browsers: `riot.util.brackets.set('#{ }')` or `riot.brackets.set('#{ }')` inmediately after load the riot instance.

I'll close this issue now, feel free to reopen it if you consider it necessary.

**Closed by aMarCruz** 2016-01-21 16:10 UTC
Labels: to verify
