### ISSUE TITLE
problem with babel and 2.3.15

### ISSUE THREAD

**Issue by jsannerstedt** [riot/compiler#35] opened 2015-12-07 14:50 UTC
Upgrading to 2.3.15 has given me some problems, not sure if it's a bug or if I need to change something.

running this code

    const riot = require('riot');
    const output = riot.compile(`
    <my-menu>
        <button onclick="{ dostuff }"></button>

        <script type="text/babel">
            const tjo = "tjim";
            this.dostuff = e => {
                console.log(e);
            };
        </script>
    </my-menu>`);
    console.log(output);

under 2.3.13 I got this

    riot.tag2('my-menu', '<button onclick="{dostuff}"></button>', '', '', function(opts) {
        var tjo = "tjim";
        this.dostuff = function (e) {
            console.log(e);
        };
    }, '{ }');

under 2.3.15 I get this

    riot.tag2('my-menu', '<button onclick="{dostuff}"></button>', '', '', function(opts) {
    const tjo = "tjim";
    this.dostuff = e => {
        console.log(e);
    };
    }, '{ }');
    
doesn't seem like it's transforming at all. What to do?

**Comment by GianlucaGuarini** [comment] 2015-12-07 14:54
@jsannerstedt you need to set your custom presets/plugins setup in the  `.babelrc` file. I recommend you to use this one https://github.com/appedemic/babel-preset-es2015-riot We will update the doc as soon as the new riot version will be released

**Comment by jsannerstedt** [comment] 2015-12-07 15:19
Thanks for the quick reply. 

However, https://www.npmjs.com/search?q=babel-preset-es2015-riot, returns no hits.

Using es2015 didn't make any difference, or do I need to do something else to get riot/babel to pick up the .babelrc file? Maybe I need something more than just the preset?

Also, we ran in to the problem just by doing a clean install of a current project, so there might be quite a few people out there with the same problem

**Comment by GianlucaGuarini** [comment] 2015-12-07 16:00
Steps to compile using riot + babel:
1 install all the [babel plugins you need](https://github.com/riot/compiler/blob/dev/.travis.yml#L15-L37)
2 Create a [`.babelrc` like this](https://github.com/riot/compiler/blob/dev/test/specs/parsers/.babelrc) file in the root of your project
3 compile your tags
@jsannerstedt  let me know if it works

**Comment by jsannerstedt** [comment] 2015-12-07 16:59
I'm sorry to say I can't make it work. Makes no difference what I put in the .babelrc... 

Created a new project, with just index.js containing the code above. installed riot and all babel-plugins, .babelrc in the root, then node index.js, still outputs unformatted js. Works with 2.3.13

**Comment by GianlucaGuarini** [comment] 2015-12-07 17:05
can you try `sudo npm install https://github.com/riot/cli.git#dev -g`? I will release a new `riot-cli` release soon

**Comment by jsannerstedt** [comment] 2015-12-07 17:30
Haven't used the cli before, but when I do "riot menu.tag" it says 
    TypeError: Cannot read property 'transform' of null

**Comment by jsannerstedt** [comment] 2015-12-07 17:32
Also, I tried modifying the compiler a bit, adding the es2015 preset to the babel transform options. Then I got

    riot.tag2('my-menu', '<button onclick="{dostuff}"></button>', '', '', function(opts) {
    "use strict";
    
    var tjo = "tjim";
    undefined.dostuff = function (e) {
        console.log(e);
    };
    }, '{ }');

so somewhat better, don't know what it's worth though...

**Comment by GianlucaGuarini** [comment] 2015-12-07 17:46
you are not using the .babelrc suggested above..

**Comment by jsannerstedt** [comment] 2015-12-07 18:35
oh yes I am, I've got a new folder, with just my index.js file, the .babelrc you provided
npm install riot
and npm install all babel plugins
doesn't work with the new compiler

**Comment by GianlucaGuarini** [comment] 2015-12-07 18:57
can You try again please? We have unpublished the new compiler: `npm install riot -g`

**Comment by jsannerstedt** [comment] 2015-12-07 19:00
yeah, the old compiler was never an issue, so that works :)

do you have any idea what went wrong though? just interested...

anyway, keep up the good work, really like this library

**Comment by GianlucaGuarini** [comment] 2015-12-07 19:05
The problem is that the new babel release is a bit a mess. With the new riot release we will update the way you can build your tags using babel. We will simply allow you to use any kind of babel plugin through the `.babelrc` file providing per default the `riot-babel-preset`. Another cool feature will be the use of a es6 [config file](https://github.com/riot/cli/blob/dev/test/fixtures/config-parsers.js) to set up your environment

**Comment by jsannerstedt** [comment] 2015-12-07 19:11
Yeah, babel keeps breaking for me all of the time. But hope you'll get it working soon, sound like great changes. Thanks for the support!

**Comment by GianlucaGuarini** [comment] 2015-12-07 19:19
no prob I am closing this issue thanks for raising it up

**Closed by GianlucaGuarini** 2015-12-07 19:19 UTC

**Comment by jsannerstedt** [comment] 2016-02-06 20:55
With the latest release of riot, this problem seems to have surfaced again.

**Comment by GianlucaGuarini** [comment] 2016-02-06 21:00
@jsannerstedt can you create a demo gist or repo I could check please?

**Comment by jsannerstedt** [comment] 2016-02-06 22:07
using riot cli, it isn't possible to compile tags that have a script with type text/babel.

https://github.com/jsannerstedt/riot-bug

**Comment by jsannerstedt** [comment] 2016-02-06 22:51
think it was just about not having all my dependencies in sync. Somehow it gave me the same error as this one. Seems to be working fine now, so never mind. Keep up the good work :)
